### ISSUE TITLE
Auto-renew certificates when close to expiring

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LetsEncrypt#11]
When certs from LE are getting close to expiring, it would be nice if this could auto-renew the certificate.

**Comment by mbican** [comment]
oh man, I didn't notice you are working on it already 🤣
never mind

**Comment by natemcmaster** [comment]
Yeah, started working on it last night. It's not done yet. https://github.com/natemcmaster/LetsEncrypt/tree/feature/renew

**Comment by SnakyBeaky** [comment]
What's the status of this feature? I can't see the branch you linked back in october.

**Comment by mbican** [comment]
I started working on it in parallel, mine, is still there https://github.com/mbican/LetsEncrypt/commit/42abd8ed130bc788310ea1f7ab6697dd0531426d I guess I could finish it, since this one is not still finished

**Comment by natemcmaster** [comment]
I deleted my branch because it was a work in progress but wasn't going the right direction. Haven't had time to work on this since then

**Comment by natemcmaster** [comment]
This is a top-requested feature, so putting this back on my plate.

Prerequisite issue: https://github.com/natemcmaster/LetsEncrypt/issues/55

**Comment by natemcmaster** [comment]
Implemented in https://github.com/natemcmaster/LetsEncrypt/pull/73. Will be released in the 0.5.0 update (coming soon)

**Comment by natemcmaster** [comment]
I'm working on a few other things. If you want to test this out sooner, here is the beta build with this change:

https://dev.azure.com/natemcmaster/github/_packaging?_a=package&feed=github%40Local&package=McMaster.AspNetCore.LetsEncrypt&protocolType=NuGet&version=0.5.0-beta.185
