### ISSUE TITLE
Using with docker

### ISSUE THREAD

**Issue by djordjedjukic** [natemcmaster/LetsEncrypt#14]
Hi,

Is it possible to use it with docker?

**Comment by natemcmaster** [comment]
Yes. 

One heads up: ideally, your server should generate a certificate once every 90 days or so, and save the certificate somewhere for faster startup and to avoid hitting Let's Encrypt rate limits. Right now, certificates are stored on disk, but I haven't provided options yet to configure _where_ on disk they are stored. So, if you are using Docker as a short-lived machine, it means you will be regenerated certificates more often than necessary. I'm using #4 to track adding more APIs for saving certificates.

Let me know if you have any other questions.

**Comment by mbican** [comment]
I use it with docker, I found out the easiest way is to mount directory with certificates to the host so they survive docker restart. Because in linux the x509store just save the certificates on disk

`docker run -v ~/x509stores/:/root/.dotnet/corefx/cryptography/x509stores/ image_name`
