### ISSUE TITLE
Publish this project to NuGet

### ISSUE THREAD

**Issue by AmbroiseCouissin** [natemcmaster/LetsEncrypt#2]
Hi there :)

Is it still named McMaster.AspNetCore.LetsEncrypt?
I couldn't find it in nuget nor in myget.

Thanks for the library!
Ambroise

**Comment by natemcmaster** [comment]
It's still a prototype. I was waiting for aspnet API to stabilize for 2.1.0 before publishing... probably should update the description to reflect that...

**Comment by AmbroiseCouissin** [comment]
Great! Thanks!

**Comment by caitchison** [comment]
Any news on releasing this now that 2.1 has been released?

**Comment by natemcmaster** [comment]
There are some design issues I want to settle before releasing anything, and haven't had enough free time lately to figure those out. I plan on releasing this to NuGet when I feel it has reached sufficient quality to be usable. I'd be happy to take PRs to help out. I'm going to organize issues into milestones to clarify my priorities in getting this to ship quality.

**Comment by natemcmaster** [comment]
I'm closing this because I ran out of time and interest to work on this project. I'm going to leave this source code out in the open. Anyone who is interested in continuing this effort, let me know. Otherwise, I'm going to archive this repo next week.

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/aspnet/KestrelHttpServer/issues/2971. Ran out of personal time and interest in working on this. Maybe I'll convince my boss to let me do this at work instead.

**Comment by natemcmaster** [comment]
Failed to convince my boss, but I've come across more time to do this, so unarchived this project and starting it again.

**Comment by razfriman** [comment]
This looks to be exactly what I need. Really hope this comes to Nuget soon

**Comment by natemcmaster** [comment]
I pushed a really early, alpha-quality release to nuget.org. https://www.nuget.org/packages/McMaster.AspNetCore.LetsEncrypt/0.1.0-alpha.12. I am _very_ interested in getting feedback on this. Here are [instructions](https://github.com/natemcmaster/LetsEncrypt/tree/d8b1abb3830a6ceca37a8bb963b3f725738d6d2a#usage) for configuring. Please give it a try and let me know how it goes!

**Comment by natemcmaster** [comment]
Done.

Decided to just go ahead and make a 'stable' release. Experience has shown very few people try pre-release packages, so I'm shippining it as 0.1.0 later today.

https://www.nuget.org/packages/McMaster.AspNetCore.LetsEncrypt

:shipit:
