### ISSUE TITLE
Adding domain name doesn't trigger certificate request

### ISSUE THREAD

**Issue by mbican** [natemcmaster/LetsEncrypt#24]
Let's assume I already have certificate for this configuration:

`"LetsEncrypt": { "DomainNames": [ "example.com" ] }`

Then I change the configuration to:

`"LetsEncrypt": { "DomainNames": [ "example.com", "www.example.com" ] }`

and restart server then the old certificate just for example.com is found and used 😢

**Comment by natemcmaster** [comment]
This seems like a good feature to add. Marking this one as up for grabs. Let me know if you're interested in implementing it

**Comment by mbican** [comment]
I'm not interested at the moment
