### ISSUE TITLE
PersistCertificatesToDirectory doesn't write to the directory

### ISSUE THREAD

**Issue by raime910** [natemcmaster/LetsEncrypt#48]
Hi, I created a new ASP.NET Core 3.1 project and called the following lines;

```
services
    .AddLetsEncrypt()
    .PersistCertificatesToDirectory(new DirectoryInfo("C:/data/MyCertificates/"), "Password123");
```

I noticed that PersistCertificatesToDirectory isn't exported yet to the package; so I went in and copied the code from there into my source. From what I understand this should write the certificate into the said directory but it is not there. Is this feature still under-development? Thanks!

**Comment by natemcmaster** [comment]
Correct, not released yet. I probably updated the readme too soon. Removed this content in https://github.com/natemcmaster/LetsEncrypt/commit/3ba55875b7536ec9b3239202d237a67873820c36.

You can try using the nightly builds from here: https://dev.azure.com/natemcmaster/github/_packaging?_a=package&feed=github%40Local&package=McMaster.AspNetCore.LetsEncrypt&protocolType=NuGet. But this API is subject to change. I think I'm going to rename before I release an update.
