### ISSUE TITLE
Consider block the site from running until cert is available

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LetsEncrypt#5]
Current prototype runs in-line with the app server, which means the server will boot and begin accepting requests over HTTP before a certificate is available. Consider supporting an alternative model which prevents the server from accepting other requests until certs are ready for use. This may be tricky since we need to still provide at least one HTTP endpoint for the HTTP challenge response.

**Comment by mbican** [comment]
If the reason is security - to avoid running the website on unencrypted http, then I would suggest to introduce "unencrypted http blocking" middleware after UseHttpsRedirection() to block http requests with e.g. 400 error

**Comment by natemcmaster** [comment]
I'm not currently planning on implementing this one. I've thought about how to implement this with kestrel, and all options are problematic. The primary problem is that Kestrel does not allow adding a port dynamically. If it did, I would have implemented this by just not serving HTTPS traffic until the cert is available...but for now, I think the current behavior is about as good as it can be.

To make dealing with this easier, I could add some kind of event notification when the cert is available so you could write code to take action on that, but I'll wait until someone requests that feature. I'm not sure how it would be used.
