### ISSUE TITLE
[Question] Where are saved certificate ?

### ISSUE THREAD

**Issue by youtpout** [natemcmaster/LetsEncrypt#53]
Hello,
I use your library with docker image, but when I redeploy my image the app request a new certificate, after multiple redeploy I have an error letencrypt request limit.
So I want to know which folder share with docker for keep certificate after redeploy ?

Thank you.

**Comment by natemcmaster** [comment]
They are saved with .NET's X509Store API. In an upcoming release, I plan to add API which will allow you to control this (see #4)

See https://github.com/dotnet/runtime/issues/27658 and https://github.com/dotnet/runtime/blob/master/docs/design/features/cross-platform-cryptography.md for more details on where .NET puts those certificates. I'm not entirely sure where they end up on disk in your docker scenario.
