### ISSUE TITLE
Persist account information

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LetsEncrypt#55]
## Problem
The current code is inefficiently creating duplicate accounts each time the server restarts or requests a new certificate. 

## Solution
Store the account key across server restarts. This will be require to enable #11

**Comment by mbican** [comment]
I think it is possible to store the account key to the certificate store, isn't it? That should be the easiest solution

**Comment by natemcmaster** [comment]
If you're referring to System.Security.Cryptography.X509Certificates.X509Store, this only supports storing X509Certificate objects. We could wrap the account key in a dummy, self-signed cert.

Currently, I'm thinking of adding new API as listed below, and providing an implementation that stores account keys to a directory on disk.

```csharp
    public class AccountModel
    {
        public string[] EmailAddresses { get; set; }
        public byte[] KeyMaterial { get; set; }
        public Uri DirectoryUri { get; set; }
    }

    public interface IAccountRepository
    {
        public Task SaveAccountAsync(AccountModel account, CancellationToken cancellationToken);
        public Task<AccountModel?> GetAccountAsync(CancellationToken cancellationToken);
    }
```
