### ISSUE TITLE
[Question] GetRequiredService<>()

### ISSUE THREAD

**Issue by Bogdancev** [natemcmaster/LetsEncrypt#60]
Hi Nate

Could you please explain why you used **GetRequiredService** in **AddLetsEncrypt** method:
```
.AddSingleton<X509CertStore>()
.AddSingleton<ICertificateSource>(x => x.GetRequiredService<X509CertStore>())
.AddSingleton<ICertificateRepository>(x => x.GetRequiredService<X509CertStore>())
```
Could it be just written like so:
```
.AddSingleton<ICertificateSource, X509CertStore>()
.AddSingleton<ICertificateRepository, X509CertStore>()
```
?

Thanx, Sergiy

**Comment by Tratcher** [comment]
That would create two instances of X509CertStore rather then sharing one, no?

**Comment by natemcmaster** [comment]
@Tratcher is right. This was done to register one object with multiple interfaces.

See https://andrewlock.net/how-to-register-a-service-with-multiple-interfaces-for-in-asp-net-core-di/ for a detailed explanation of this.

**Comment by Bogdancev** [comment]
Thanx
