### ISSUE TITLE
[Question] ASP.NET Core Shared hosting

### ISSUE THREAD

**Issue by Bogdancev** [natemcmaster/LetsEncrypt#61]
Hi

I'm trying it on [https://absolutehosting.co.za/#windows-hosting-south-africa](https://absolutehosting.co.za/#windows-hosting-south-africa) (about 1$ a month)

And receive message from this path of the code:
```
if (_config.GetValue<bool>("UseIISIntegration"))
{
    _logger.LogWarning("LetsEncrypt does not work with apps hosting in IIS. IIS does not allow for dynamic HTTPS certificate binding, " +
        "so if you want to use Let's Encrypt, you'll need to use a different tool to do so.");
    return Task.CompletedTask;
}
```
Does this mean **ASP.NET Core with IIS**  Web Server Scenario (the second option on the home page of this project) and thus I cannot use it?
Or it cannot be used with any windows shared hosting at all?

Thanx

**Comment by natemcmaster** [comment]
Yes, that is what this message means. Sorry, you’ll need to find a different way to get your HTTPS certs installed.

**Comment by Bogdancev** [comment]
Thanx
