### ISSUE TITLE
How to use LetsEncrypt with Azure

### ISSUE THREAD

**Issue by Josvds** [natemcmaster/LetsEncrypt#62]
I have two projects for which I would like to use LetsEncrypt. I used this project already on my home network to try it out and it worked fine. But when moving it to Azure I can't get it to work.

I did read something about " Azure App Services (aka WebApps) often runs older versions of ASP.NET Core in a reverse proxy.", but I`m not exactly sure what this means.
I am using .NET core 3.1 (so the latest version) and running it inside a Docker container, so is this then ok and should this work?

Because when I was using it the console output told me that calling for .well-known path returned a 404. While when opening the same URL my self, it returned the file correctly. So I`m not sure if it won't work because its on Azure or if I have configured something wrong?

**Comment by natemcmaster** [comment]
Can you be more specific? There are a handful of ways to use containers on Azure. https://azure.microsoft.com/en-us/product-categories/containers/ - which of these are you using?

**Comment by Josvds** [comment]
I`m pushing the container to "Container Registry" and then it is started in "App Service". But is another option (which supports containers) working? Because for me its not required to have app service. Currently I run this on my local network on docker which works fine.

**Comment by natemcmaster** [comment]
I'm not exactly sure how App Service uses Docker containers, but if its anything like App Service on Windows, there is probably a reverse proxy in-front of the container...which would fall into the unsupportable scenarios for this project.

You could use Azure Container Instances instead and expose the container directly to the internet. I did that in some tests and it worked, but you lose some of the other benefits of App Service, like integrated diagnostics tools. I'd be willing to bet there are other ways to get a let's encrypt HTTPS cert in Linux App Service, but I don't know for sure how to set that up. If you find out, let me know and I can add it to the links in the readme of this repo.

**Comment by Josvds** [comment]
Ok.. I`m also not sure. But when I find out a route, I will let you know. Thanks for your help. And of course your nice project which helped me already a lot.
