### ISSUE TITLE
Allow for custom ports to be used to request a certificate

### ISSUE THREAD

**Issue by lewcianci** [natemcmaster/LetsEncrypt#70]
I'm trying to run my solution out of a docker container that is served to the outside world on ports 8080 and 8043 (for http and https).  There doesn't appear to be a way to specify a custom port for Let's Encrypt to deliver a certificate for, the request just times out.

It would be good if there was a way to configure what port your service was running on, so then the ACME server could find the server in the right place and the enrollment could suceed.

I'm happy to submit a PR for this if you could give me some tips on what part of this package handles this functionality :)

**Comment by jesseborden** [comment]
> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

https://letsencrypt.org/docs/challenge-types/

**Comment by bordenit** [comment]
> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

https://letsencrypt.org/docs/challenge-types/

**Comment by lewcianci** [comment]
Ah yeah that's a me thing, and why you should read the docs before opening an issue haha.

I fixed this by going the DNS-01 route, now everything works :) Thanks!
