### ISSUE TITLE
Clarify the required "accept terms and conditions" behavior

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LetsEncrypt#9]
Does Let's Encrypt still require explicit user interaction to confirm they have accepted the terms and conditions? I added this because I remember @mholt put something like this in Caddy, but I didn't actually investigate if this is still required.

**Comment by mholt** [comment]
Yeah, as far as I know, nothing changed. Caddy requires explicit agreement either by passing an interactive prompt or using the -agree flag. I tried to make it implicit at download-time but they wouldn't have it.

**Comment by natemcmaster** [comment]
Ok, that's what I remember you saying. I didn't see this mentioned in their guide https://letsencrypt.org/docs/integration-guide/. Is there some other place this expectation is stated?

**Comment by mholt** [comment]
It's built into the protocol...
